[package]
name = "ffd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.0"
ndarray = "0.14"
ndarray-linalg = { version = "0.13", features = ["openblas"] }

